#
# MySQL
#
#jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
#jdbc.default.url=jdbc:mysql://localhost/lportal
#jdbc.default.username=root
#jdbc.default.password=

#
# Input a list of comma delimited email addresses that will be blacklisted
# when sending emails. The specified email addresses will be ignored and a
# warning will be logged.
#
# Env: LIFERAY_MAIL_PERIOD_SEND_PERIOD_BLACKLIST
#
mail.send.blacklist=
#mail.send.blacklist=\
#        noreply@liferay.com,\
#        test@liferay.com,\
#        noreply@domain.invalid,\
#        test@domain.invalid


# Custom Calendar Web Fragment properties
custom.calendar.from.address=christian.berndt@liferay.com
custom.calendar.from.name=Christian Berndt